"""campos adicionais de prefeitura

Revision ID: 0abd5051dae3
Revises: 81675ec28de0
Create Date: 2026-10-01 00:10:00.193939

"""
from alembic import op
import sqlalchemy as sa


revision = '0abd5051dae3'
down_revision = '81675ec28de0'
branch_labels = None
depends_on = None


def upgrade():
    # NÃO dropar 'spatial_ref_sys' — tabela de sistema do PostGIS.
    op.add_column('prefeituras', sa.Column('porte', sa.String(length=50), nullable=True))
    op.add_column('prefeituras', sa.Column('inscricao_estadual', sa.String(length=30), nullable=True))
    op.add_column('prefeituras', sa.Column('ramo_atividade', sa.String(length=150), nullable=True))
    op.add_column('prefeituras', sa.Column('complemento', sa.String(length=100), nullable=True))
    op.add_column('prefeituras', sa.Column('fax', sa.String(length=20), nullable=True))
    op.add_column('prefeituras', sa.Column('contato_nome', sa.String(length=150), nullable=True))
    op.add_column('prefeituras', sa.Column('contato_telefone', sa.String(length=20), nullable=True))
    op.add_column('prefeituras', sa.Column('contato_fax', sa.String(length=20), nullable=True))
    op.add_column('prefeituras', sa.Column('observacoes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prefeituras', 'observacoes')
    op.drop_column('prefeituras', 'contato_fax')
    op.drop_column('prefeituras', 'contato_telefone')
    op.drop_column('prefeituras', 'contato_nome')
    op.drop_column('prefeituras', 'fax')
    op.drop_column('prefeituras', 'complemento')
    op.drop_column('prefeituras', 'ramo_atividade')
    op.drop_column('prefeituras', 'inscricao_estadual')
    op.drop_column('prefeituras', 'porte')
