"""cidades bairros prefeituras atividades mao_obra

Revision ID: 322ce3e62f74
Revises: bf679f3ae4a0
Create Date: 2026-09-30 23:54:04.024047

"""
from alembic import op
import sqlalchemy as sa


revision = '322ce3e62f74'
down_revision = 'bf679f3ae4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cidades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mao_obra',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('funcao', sa.String(length=100), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bairros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cidade_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prefeituras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=300), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('bairro_id', sa.UUID(), nullable=True),
    sa.Column('cidade_id', sa.UUID(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bairro_id'], ['bairros.id'], ),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NÃO dropar 'spatial_ref_sys' — tabela de sistema do PostGIS.
    op.add_column('contratos', sa.Column('prefeitura_id', sa.UUID(), nullable=False))
    op.create_foreign_key('fk_contratos_prefeitura_id', 'contratos', 'prefeituras', ['prefeitura_id'], ['id'])
    op.drop_column('contratos', 'prefeitura_cnpj')
    op.drop_column('contratos', 'prefeitura_nome')
    op.add_column('pedidos_manutencao', sa.Column('atividade_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_pedidos_manutencao_atividade_id', 'pedidos_manutencao', 'atividades', ['atividade_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pedidos_manutencao_atividade_id', 'pedidos_manutencao', type_='foreignkey')
    op.drop_column('pedidos_manutencao', 'atividade_id')
    op.add_column('contratos', sa.Column('prefeitura_nome', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('contratos', sa.Column('prefeitura_cnpj', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint('fk_contratos_prefeitura_id', 'contratos', type_='foreignkey')
    op.drop_column('contratos', 'prefeitura_id')
    op.drop_table('prefeituras')
    op.drop_table('bairros')
    op.drop_table('mao_obra')
    op.drop_table('cidades')
    op.drop_table('atividades')
    # ### end Alembic commands ###
