"""veiculo: ano fabricacao/modelo, cor, renavam, acessorios

Revision ID: 92271115a90d
Revises: 8d079fd8c8f9
Create Date: 2026-10-01 01:45:48.497619

"""
from alembic import op
import sqlalchemy as sa


revision = '92271115a90d'
down_revision = '8d079fd8c8f9'
branch_labels = None
depends_on = None


def upgrade():
    # NÃO dropar 'spatial_ref_sys' — tabela de sistema do PostGIS.
    op.add_column('veiculos', sa.Column('ano_fabricacao', sa.Integer(), nullable=True))
    op.add_column('veiculos', sa.Column('ano_modelo', sa.Integer(), nullable=True))
    op.add_column('veiculos', sa.Column('cor', sa.String(length=30), nullable=True))
    op.add_column('veiculos', sa.Column('renavam', sa.String(length=11), nullable=True))
    op.add_column('veiculos', sa.Column('acessorios', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('veiculos', 'acessorios')
    op.drop_column('veiculos', 'renavam')
    op.drop_column('veiculos', 'cor')
    op.drop_column('veiculos', 'ano_modelo')
    op.drop_column('veiculos', 'ano_fabricacao')
