"""execucao reclamacao, equipe api, categoria material

Revision ID: b533ec76ec27
Revises: 736b1956946f
Create Date: 2026-10-01 11:17:27.258519

"""
from alembic import op
import sqlalchemy as sa


revision = 'b533ec76ec27'
down_revision = '736b1956946f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execucoes_reclamacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reclamacao_id', sa.UUID(), nullable=False),
    sa.Column('data_execucao', sa.Date(), nullable=False),
    sa.Column('equipe_dia_id', sa.UUID(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipe_dia_id'], ['equipes_dia.id'], ),
    sa.ForeignKeyConstraint(['reclamacao_id'], ['reclamacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_execucao_material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execucao_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('movimento', sa.Enum('INSTALADO', 'RETIRADO', name='movimentomaterial'), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo_lampada', sa.String(length=100), nullable=True),
    sa.Column('potencia_w', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes_reclamacao.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'materiais', sa.Column('categoria', sa.String(length=20), nullable=False, server_default='GERAL')
    )
    op.alter_column('materiais', 'categoria', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    op.drop_column('materiais', 'categoria')
    op.drop_table('itens_execucao_material')
    op.drop_table('execucoes_reclamacao')
