"""schema inicial

Revision ID: d859b3641c69
Revises: 
Create Date: 2026-09-30 23:33:32.207792

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = 'd859b3641c69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prefeitura_nome', sa.String(length=200), nullable=False),
    sa.Column('prefeitura_cnpj', sa.String(length=20), nullable=True),
    sa.Column('numero_contrato', sa.String(length=50), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('funcao', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('materiais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.Enum('ADMIN', 'USUARIO', name='papelusuario'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('permissoes_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('ativos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contrato_id', sa.UUID(), nullable=False),
    sa.Column('codigo_ponto', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('logradouro', sa.String(length=300), nullable=True),
    sa.Column('bairro', sa.String(length=120), nullable=True),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('potencia_watts', sa.Integer(), nullable=True),
    sa.Column('tecnologia', sa.String(length=50), nullable=True),
    sa.Column('data_instalacao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Índice GiST em 'geom' já é criado automaticamente pelo GeoAlchemy2 ao
    # criar a tabela (DDL event) — criar de novo aqui dá "já existe".
    op.create_table('equipes_dia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('veiculo_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precos_ponto',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contrato_id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.Enum('MANUTENCAO', 'OBRAS', name='categoriapreco'), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vigencia_inicio', sa.Date(), nullable=False),
    sa.Column('vigencia_fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipe_membros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipe_dia_id', sa.UUID(), nullable=False),
    sa.Column('funcionario_id', sa.UUID(), nullable=False),
    sa.Column('papel', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['equipe_dia_id'], ['equipes_dia.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordens_servico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contrato_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('OSM', 'OSO', name='tipoos'), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('data_abertura', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'VALIDADA', 'FECHADA', 'CANCELADA', name='statusos'), nullable=False),
    sa.Column('equipe_dia_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['equipe_dia_id'], ['equipes_dia.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('pedidos_manutencao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contrato_id', sa.UUID(), nullable=False),
    sa.Column('ativo_id', sa.UUID(), nullable=True),
    sa.Column('origem', sa.Enum('ESCRITORIO', 'CAMPO', name='origempedido'), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'EM_EXECUCAO', 'EXECUTADO', 'VALIDADO', 'CANCELADO', name='statuspedido'), nullable=False),
    sa.Column('endereco_livre', sa.String(length=300), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_por_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execucoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uuid_local', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('equipe_dia_id', sa.UUID(), nullable=True),
    sa.Column('preco_ponto_id', sa.UUID(), nullable=True),
    sa.Column('data_execucao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('validado_por_id', sa.UUID(), nullable=True),
    sa.Column('validado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sincronizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipe_dia_id'], ['equipes_dia.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_manutencao.id'], ),
    sa.ForeignKeyConstraint(['preco_ponto_id'], ['precos_ponto.id'], ),
    sa.ForeignKeyConstraint(['validado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid_local')
    )
    op.create_table('itens_ordem_servico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ordem_servico_id', sa.UUID(), nullable=False),
    sa.Column('tipo_item', sa.Enum('PONTO', 'MATERIAL', name='tipoitem'), nullable=False),
    sa.Column('preco_ponto_id', sa.UUID(), nullable=True),
    sa.Column('material_id', sa.UUID(), nullable=True),
    sa.Column('ativo_id', sa.UUID(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['preco_ponto_id'], ['precos_ponto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execucao_id', sa.UUID(), nullable=False),
    sa.Column('arquivo_path', sa.String(length=500), nullable=False),
    sa.Column('momento', sa.String(length=10), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NÃO dropar 'spatial_ref_sys' — é tabela de sistema do PostGIS (a extensão
    # cria sozinha); o autogenerate detecta como "removida" por não estar nos
    # nossos models, mas nunca deve ser tocada por migration da aplicação.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fotos')
    op.drop_table('itens_ordem_servico')
    op.drop_table('execucoes')
    op.drop_table('pedidos_manutencao')
    op.drop_table('ordens_servico')
    op.drop_table('equipe_membros')
    op.drop_table('precos_ponto')
    op.drop_table('equipes_dia')
    op.drop_table('ativos')
    op.drop_table('veiculos')
    op.drop_table('usuarios')
    op.drop_table('materiais')
    op.drop_table('funcionarios')
    op.drop_table('contratos')
    # ### end Alembic commands ###
