"""nova tabela reclamacoes

Revision ID: f0b58798eeec
Revises: 4037e6863e28
Create Date: 2026-10-01 10:16:57.749327

"""
from alembic import op
import sqlalchemy as sa


revision = 'f0b58798eeec'
down_revision = '4037e6863e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reclamacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_reclamante', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo_reclamacao', sa.String(length=30), nullable=False),
    sa.Column('data_reclamacao', sa.Date(), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('logradouro', sa.String(length=300), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('ponto_referencia', sa.String(length=200), nullable=True),
    sa.Column('bairro_id', sa.UUID(), nullable=True),
    sa.Column('cidade_id', sa.UUID(), nullable=True),
    sa.Column('prefeitura_id', sa.UUID(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bairro_id'], ['bairros.id'], ),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], ),
    sa.ForeignKeyConstraint(['prefeitura_id'], ['prefeituras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NÃO dropar 'spatial_ref_sys' — tabela de sistema do PostGIS.


def downgrade():
    op.drop_table('reclamacoes')
